name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: What are you trying to do that's awkward or impossible today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like warp-gui to do?
    validations:
      required: false
  - type: checkboxes
    id: scope
    attributes:
      label: Scope check
      description: warp-gui is a front-end for the official warp-cli.
      options:
        - label: This can be done via warp-cli (it doesn't require bundling or modifying Cloudflare software).
          required: false
